name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'

      - name: Publish to GitHub Packages
        run: go list -m all | grep github.com/BeloTechnologies/session-core | xargs -n 1 go get
        env:
          GOPROXY: https://npm.pkg.github.com
          GITHUB_TOKEN: ${{ secrets.BELO_CI }}
